language:        python
cache:           pip
dist:            xenial

matrix:
  include:
    - python:    3.6
      env:       TOXENV=py36
    - python:    3.7
      env:       TOXENV=py37
    - python:    3.8
      env:       TOXENV=py38
    - python:    3.6
      env:       TOXENV=docs
    - python:    3.6
      env:       TOXENV=coveralls

branches:
  only:
    - master
    - develop

before_install:
  - echo $TRAVIS_PYTHON_VERSION

services:
  - postgresql

install:
  - pip install --upgrade pip
  - pip install tox-travis
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

before_script:
  - export FLASK_CONFIG=travis
  - export FLASK_APP="$TRAVIS_BUILD_DIR/fhe_collector"
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres

script:
  - tox

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - mail@stefankasberger.at
    on_success: change
