language: python
cache: pip
dist: xenial

sudo: false

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=coverage
    - python: 3.6
      env: TOXENV=coveralls
    - python: 3.6
      env: TOXENV=packaging

branches:
  only:
    - master
    - develop

before_install:
  - echo $TRAVIS_PYTHON_VERSION
  - export ENV=testing

services: postgresql

install:
  - pip install tox-travis
  - pip install coverage
  - pip install coveralls
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - "pip install -r requirements.txt"

before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/fhe.py"
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - export FLASK_DEBUG=1

script:
  - tox

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - mail@stefankasberger.at
    on_success: change
