"""re-factor models

Revision ID: 0d85a668b602
Revises: 947aad10a260
Create Date: 2019-08-14 18:16:07.840582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d85a668b602'
down_revision = '947aad10a260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doi', sa.Column('url_doi_lp', sa.Boolean(), nullable=False))
    op.add_column('doi', sa.Column('url_doi_new', sa.Boolean(), nullable=False))
    op.add_column('doi', sa.Column('url_doi_old', sa.Boolean(), nullable=False))
    op.add_column('doi', sa.Column('url_pm', sa.Boolean(), nullable=False))
    op.add_column('doi', sa.Column('url_pmc', sa.Boolean(), nullable=False))
    op.add_column('doi', sa.Column('url_unpaywall', sa.Boolean(), nullable=False))
    op.drop_column('doi', 'unpaywall_url')
    op.drop_column('doi', 'pmc_url')
    op.drop_column('doi', 'doi_old_url')
    op.drop_column('doi', 'doi_new_url')
    op.drop_column('doi', 'doi_lp_url')
    op.drop_column('doi', 'pm_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doi', sa.Column('pm_url', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('doi', sa.Column('doi_lp_url', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('doi', sa.Column('doi_new_url', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('doi', sa.Column('doi_old_url', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('doi', sa.Column('pmc_url', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('doi', sa.Column('unpaywall_url', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('doi', 'url_unpaywall')
    op.drop_column('doi', 'url_pmc')
    op.drop_column('doi', 'url_pm')
    op.drop_column('doi', 'url_doi_old')
    op.drop_column('doi', 'url_doi_new')
    op.drop_column('doi', 'url_doi_lp')
    # ### end Alembic commands ###
