"""add date to Doi()

Revision ID: 1298d4abb0d2
Revises: 3a9187de44b2
Create Date: 2019-04-28 17:33:27.209452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1298d4abb0d2'
down_revision = '3a9187de44b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doi', sa.Column('date_published', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doi', 'date_published')
    # ### end Alembic commands ###
