"""empty message

Revision ID: 1a7a23887ebf
Revises: dd5cb98388ae
Create Date: 2018-03-20 20:31:41.755601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7a23887ebf'
down_revision = 'dd5cb98388ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('doi_resolve_error', sa.String(length=128), nullable=True))
    op.add_column('publication', sa.Column('doi_resolve_status', sa.String(length=128), nullable=True))
    op.add_column('publication', sa.Column('doi_resolve_ts', sa.Date(), nullable=True))
    op.add_column('publication', sa.Column('doi_url', sa.String(length=128), nullable=True))
    op.add_column('publication', sa.Column('ncbi_errmsg', sa.String(length=128), nullable=True))
    op.add_column('publication', sa.Column('ncbi_ts', sa.Date(), nullable=True))
    op.add_column('publication', sa.Column('pmc', sa.String(length=128), nullable=True))
    op.add_column('publication', sa.Column('pmid', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'pmid')
    op.drop_column('publication', 'pmc')
    op.drop_column('publication', 'ncbi_ts')
    op.drop_column('publication', 'ncbi_errmsg')
    op.drop_column('publication', 'doi_url')
    op.drop_column('publication', 'doi_resolve_ts')
    op.drop_column('publication', 'doi_resolve_status')
    op.drop_column('publication', 'doi_resolve_error')
    # ### end Alembic commands ###
