"""undo unique of pmc_id and pm_id in Doi

Revision ID: 3a9187de44b2
Revises: 94d68bc0af3b
Create Date: 2019-04-28 04:44:02.858037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9187de44b2'
down_revision = '94d68bc0af3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('doi_pm_id_key', 'doi', type_='unique')
    op.drop_constraint('doi_pmc_id_key', 'doi', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('doi_pmc_id_key', 'doi', ['pmc_id'])
    op.create_unique_constraint('doi_pm_id_key', 'doi', ['pm_id'])
    # ### end Alembic commands ###
