"""Add import class to store import information

Revision ID: 4a3a663ce25d
Revises: 31b2bd98a0e9
Create Date: 2019-03-04 23:49:38.698552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a3a663ce25d'
down_revision = '31b2bd98a0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('doi', sa.Column('import_id', sa.Integer(), nullable=False))
    op.add_column('doi', sa.Column('pm_id', sa.String(length=256), nullable=True))
    op.add_column('doi', sa.Column('pmc_id', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'doi', ['pm_id'])
    op.create_unique_constraint(None, 'doi', ['pmc_id'])
    op.create_foreign_key(None, 'doi', 'import', ['import_id'], ['id'])
    op.drop_column('doi', 'source_json')
    op.drop_column('doi', 'source_file')
    op.drop_column('doi', 'imported_at')
    op.drop_column('doi', 'source_type')
    op.drop_column('url', 'url_source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('url_source', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('doi', sa.Column('source_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('doi', sa.Column('imported_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('doi', sa.Column('source_file', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('doi', sa.Column('source_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doi', type_='foreignkey')
    op.drop_constraint(None, 'doi', type_='unique')
    op.drop_constraint(None, 'doi', type_='unique')
    op.drop_column('doi', 'pmc_id')
    op.drop_column('doi', 'pm_id')
    op.drop_column('doi', 'import_id')
    op.drop_table('import')
    # ### end Alembic commands ###
