"""remove all objects from datamodel except doi

Revision ID: 7eb1ec7367a6
Revises: d9fa00a382dd
Create Date: 2018-11-21 22:08:35.224499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7eb1ec7367a6'
down_revision = 'd9fa00a382dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doi',
    sa.Column('doi', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('source_type', sa.String(length=256), nullable=True),
    sa.Column('source_json', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('doi')
    )
    op.drop_table('facebook_response')
    op.drop_table('publication')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication',
    sa.Column('doi', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('pub_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('facebook_response',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='facebook_response_pkey')
    )
    op.drop_table('doi')
    # ### end Alembic commands ###
