"""test out: change nullable in some columns of models #2

Revision ID: 89704eafcc6e
Revises: c2c48988fe1c
Create Date: 2019-03-05 00:39:55.561204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89704eafcc6e'
down_revision = 'c2c48988fe1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doi', 'import_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('doi', 'pm_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('doi', 'pmc_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('url', 'doi',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url', 'doi',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('doi', 'pmc_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('doi', 'pm_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('doi', 'import_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
