"""empty message

Revision ID: 94d68bc0af3b
Revises: e79ada5aaeb7
Create Date: 2019-04-28 02:12:02.029065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d68bc0af3b'
down_revision = 'e79ada5aaeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doi',
    sa.Column('doi', sa.String(length=64), nullable=False),
    sa.Column('pmc_id', sa.String(length=256), nullable=True),
    sa.Column('pm_id', sa.String(length=256), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['import.id'], ),
    sa.PrimaryKeyConstraint('doi'),
    sa.UniqueConstraint('pm_id'),
    sa.UniqueConstraint('pmc_id')
    )
    op.create_table('url',
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('doi', sa.String(length=64), nullable=False),
    sa.Column('url_type', sa.String(length=32), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doi'], ['doi.doi'], ),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('fb_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_url', sa.String(length=512), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('reactions', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('plugin_comments', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['url_url'], ['url.url'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fb_request')
    op.drop_table('url')
    op.drop_table('doi')
    op.drop_table('import')
    # ### end Alembic commands ###
