"""test

Revision ID: c3c6bfa6d85b
Revises: 7eb1ec7367a6
Create Date: 2018-11-21 22:14:13.297456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c6bfa6d85b'
down_revision = '7eb1ec7367a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doi', sa.Column('source_tmp', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doi', 'source_tmp')
    # ### end Alembic commands ###
