"""update Publication

Revision ID: dd5cb98388ae
Revises: 1f25d2e2ed47
Create Date: 2018-03-20 16:48:23.505180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5cb98388ae'
down_revision = '1f25d2e2ed47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'date')
    # ### end Alembic commands ###
