"""fix issue: increase string length of source in Import() class to 512 #3

Revision ID: ee7547dfc619
Revises: 89704eafcc6e
Create Date: 2019-03-05 00:50:56.543790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee7547dfc619'
down_revision = '89704eafcc6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doi', 'import_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('doi', 'pm_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('doi', 'pmc_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('import', 'imported_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('import', 'source',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('url', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('url', 'doi',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('url', 'url_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url', 'url_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('url', 'doi',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('url', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('import', 'source',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('import', 'imported_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('doi', 'pmc_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('doi', 'pm_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('doi', 'import_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
