"""update doi object

Revision ID: f0e98c6a7fba
Revises: c3c6bfa6d85b
Create Date: 2018-11-21 22:55:49.210836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e98c6a7fba'
down_revision = 'c3c6bfa6d85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doi', 'source_tmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doi', sa.Column('source_tmp', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
