"""update url and doi attributes

Revision ID: f6102dc58c7f
Revises: 776edda4b9fa
Create Date: 2019-08-14 16:57:09.992950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6102dc58c7f'
down_revision = '776edda4b9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=64), nullable=False),
    sa.Column('request_url', sa.String(length=512), nullable=True),
    sa.Column('request_type', sa.String(length=32), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.Column('response_status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['doi'], ['doi.doi'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_request')
    # ### end Alembic commands ###
